In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('Practise').getOrCreate()

In [3]:
spark

In [13]:
df_pyspark = spark.read.csv('test1.csv')

In [ ]:
df_pyspark

In [15]:
df_pyspark.show()

+---------+---+----------+------+
|      _c0|_c1|       _c2|   _c3|
+---------+---+----------+------+
|     Name|age|Experience|Salary|
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

## read.option

In [16]:
dfSpark = spark.read.option('header','true').csv('test1.csv')

In [18]:
dfSpark.show()

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

In [19]:
type(dfSpark)

pyspark.sql.dataframe.DataFrame

In [20]:
dfSpark.head(3)

[Row(Name='Krish', age='31', Experience='10', Salary='30000'),
 Row(Name='Sudhanshu', age='30', Experience='8', Salary='25000'),
 Row(Name='Sunny', age='29', Experience='4', Salary='20000')]

In [21]:
dfSpark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: string (nullable = true)
 |-- Experience: string (nullable = true)
 |-- Salary: string (nullable = true)

In [23]:
dfSpark[['Name','Age']]

DataFrame[Name: string, Age: string]

In [24]:
dfSpark[['Name','Age']].head(3)

[Row(Name='Krish', Age='31'),
 Row(Name='Sudhanshu', Age='30'),
 Row(Name='Sunny', Age='29')]

In [27]:
dfSpark[['Name','Age']].show(2)

+---------+---+
|     Name|Age|
+---------+---+
|    Krish| 31|
|Sudhanshu| 30|
+---------+---+
only showing top 2 rows

In [28]:
dfSpark.show(3)

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
+---------+---+----------+------+
only showing top 3 rows

## Data types

In [30]:
dfSpark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: string (nullable = true)
 |-- Experience: string (nullable = true)
 |-- Salary: string (nullable = true)

In [32]:
dfSpark = spark.read.option('header','true').\
csv('test1.csv',inferSchema = True)

In [33]:
dfSpark.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [34]:
dfSpark.show()

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

In [35]:
type(dfSpark)

pyspark.sql.dataframe.DataFrame

In [37]:
dfSpark.head(3)

[Row(Name='Krish', age=31, Experience=10, Salary=30000),
 Row(Name='Sudhanshu', age=30, Experience=8, Salary=25000),
 Row(Name='Sunny', age=29, Experience=4, Salary=20000)]

## Selecionar uma coluna

In [38]:
dfSpark.select('Name')

DataFrame[Name: string]

In [41]:
dfSpark.select('Name').show()

+---------+
|     Name|
+---------+
|    Krish|
|Sudhanshu|
|    Sunny|
|     Paul|
|   Harsha|
|  Shubham|
+---------+

In [39]:
dfSpark[['Name']]

DataFrame[Name: string]

In [40]:
dfSpark[['Name']].show()

+---------+
|     Name|
+---------+
|    Krish|
|Sudhanshu|
|    Sunny|
|     Paul|
|   Harsha|
|  Shubham|
+---------+

### multiple

In [43]:
dfSpark.select(['Name','Experience']).show()

+---------+----------+
|     Name|Experience|
+---------+----------+
|    Krish|        10|
|Sudhanshu|         8|
|    Sunny|         4|
|     Paul|         3|
|   Harsha|         1|
|  Shubham|         2|
+---------+----------+

In [42]:
dfSpark[['Name','Age']].show()

+---------+---+
|     Name|Age|
+---------+---+
|    Krish| 31|
|Sudhanshu| 30|
|    Sunny| 29|
|     Paul| 24|
|   Harsha| 21|
|  Shubham| 23|
+---------+---+

## column name

In [47]:
dfSpark['Name']

Column<b'Name'>

In [48]:
dfSpark[['Name']]

DataFrame[Name: string]

## As pandas

In [45]:
dfSpark.toPandas().head()

        Name  age  Experience  Salary
0      Krish   31          10   30000
1  Sudhanshu   30           8   25000
2      Sunny   29           4   20000
3       Paul   24           3   20000
4     Harsha   21           1   15000

In [46]:
dfSpark.toPandas()[['Name']]

        Name
0      Krish
1  Sudhanshu
2      Sunny
3       Paul
4     Harsha
5    Shubham

## dtypes

In [54]:
dfSpark.dtypes

[('Name', 'string'), ('age', 'int'), ('Experience', 'int'), ('Salary', 'int')]

## Describe

In [56]:
dfSpark.describe()

DataFrame[summary: string, Name: string, age: string, Experience: string, Salary: string]

In [62]:
dfSpark.describe().toPandas()

  summary    Name                 age         Experience              Salary
0   count       6                   6                  6                   6
1    mean    None  26.333333333333332  4.666666666666667  21333.333333333332
2  stddev    None   4.179314138308661  3.559026084010437   5354.126134736337
3     min  Harsha                  21                  1               15000
4     max   Sunny                  31                 10               30000

# Transformacoes

## Adding columns

In [65]:
dfSpark.show()

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

In [66]:
dfSpark.withColumn('experience_after_2_years',dfSpark['Experience']+2)

DataFrame[Name: string, age: int, Experience: int, Salary: int, experience_after_2_years: int]

In [67]:
dfSpark.show()

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
|  Shubham| 23|         2| 18000|
+---------+---+----------+------+

In [68]:
dfSpark.withColumn('experience_after_2_years',dfSpark['Experience']+2).show()

+---------+---+----------+------+------------------------+
|     Name|age|Experience|Salary|experience_after_2_years|
+---------+---+----------+------+------------------------+
|    Krish| 31|        10| 30000|                      12|
|Sudhanshu| 30|         8| 25000|                      10|
|    Sunny| 29|         4| 20000|                       6|
|     Paul| 24|         3| 20000|                       5|
|   Harsha| 21|         1| 15000|                       3|
|  Shubham| 23|         2| 18000|                       4|
+---------+---+----------+------+------------------------+

In [69]:
dfSpark.withColumn('age_by_experience',dfSpark['age']/dfSpark['Experience']).show()

+---------+---+----------+------+-----------------+
|     Name|age|Experience|Salary|age_by_experience|
+---------+---+----------+------+-----------------+
|    Krish| 31|        10| 30000|              3.1|
|Sudhanshu| 30|         8| 25000|             3.75|
|    Sunny| 29|         4| 20000|             7.25|
|     Paul| 24|         3| 20000|              8.0|
|   Harsha| 21|         1| 15000|             21.0|
|  Shubham| 23|         2| 18000|             11.5|
+---------+---+----------+------+-----------------+

In [74]:
dfSpark = dfSpark.withColumn('age_by_experience',dfSpark['age']/dfSpark['Experience'])

In [75]:
dfSpark.show()

+---------+---+----------+------+-----------------+
|     Name|age|Experience|Salary|age_by_experience|
+---------+---+----------+------+-----------------+
|    Krish| 31|        10| 30000|              3.1|
|Sudhanshu| 30|         8| 25000|             3.75|
|    Sunny| 29|         4| 20000|             7.25|
|     Paul| 24|         3| 20000|              8.0|
|   Harsha| 21|         1| 15000|             21.0|
|  Shubham| 23|         2| 18000|             11.5|
+---------+---+----------+------+-----------------+

In [76]:
dfSpark

DataFrame[Name: string, age: int, Experience: int, Salary: int, age_by_experience: double]

## drop columns

In [78]:
dfSpark = dfSpark.drop('age_by_experience')

In [80]:
dfSpark.show(5)

+---------+---+----------+------+
|     Name|age|Experience|Salary|
+---------+---+----------+------+
|    Krish| 31|        10| 30000|
|Sudhanshu| 30|         8| 25000|
|    Sunny| 29|         4| 20000|
|     Paul| 24|         3| 20000|
|   Harsha| 21|         1| 15000|
+---------+---+----------+------+
only showing top 5 rows

## Rename columns

In [81]:
dfSpark = dfSpark.withColumnRenamed('Name','new_name')

In [83]:
dfSpark.toPandas()

    new_name  age  Experience  Salary
0      Krish   31          10   30000
1  Sudhanshu   30           8   25000
2      Sunny   29           4   20000
3       Paul   24           3   20000
4     Harsha   21           1   15000
5    Shubham   23           2   18000